from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard_view, name="dashboard"),
    path("api/dashboard/summary/", views.dashboard_summary_api, name="summary_api"),
    path("camera/", views.camera_view, name="camera"),
    path("camera/stream/<str:cam_id>/", views.camera_stream, name="camera_stream"),
    path("live/start/", views.live_start, name="live_start"),
    path("live/stop/", views.live_stop, name="live_stop"),
    path("live/status/", views.live_status, name="live_status"),
    path("live/save/", views.live_save, name="live_save"),
    path("live/stream/<str:cam_id>/", views.live_annotated_stream, name="live_stream"),
    path("machine/", views.machine_view, name="machine"),
    path("quality/", views.quality_home, name="quality"),
    path("quality/evaluate/", views.evaluate_image, name="quality_evaluate"),
    path("quality/batch/<int:batch_id>/", views.quality_batch_detail, name="quality_batch_detail"),
    path("aroma/", views.aroma_view, name="aroma"),
    path("batch/", views.batch_metrics_view, name="batch"),
    path("api/batch-metrics/summary/", views.batch_metrics_summary_api, name="batch_metrics_summary_api"),
    path("packaging/", views.packaging_view, name="packaging"),
    path("api/packaging/summary/", views.packaging_summary_api, name="packaging_summary_api"),
    path("api/packaging/list/", views.packaging_list_api, name="packaging_list_api"),
    path("api/packaging/<int:batch_id>/", views.packaging_detail_api, name="packaging_detail_api"),
    path("api/packaging/<int:batch_id>/update/", views.packaging_update_api, name="packaging_update_api"),
    path("activity/", views.activity_log_view, name="activity"),
    path("api/activity/list/", views.activity_logs_list_api, name="activity_logs_list_api"),
    path("api/activity/<int:log_id>/", views.activity_log_detail_api, name="activity_log_detail_api"),
    path("api/activity/users/", views.activity_logs_users_api, name="activity_logs_users_api"),
    path("reports/", views.reports_view, name="reports"),
    path("api/reports/lote/<int:batch_id>/", views.reports_lote_api, name="reports_lote_api"),
    path("api/reports/month/", views.reports_month_api, name="reports_month_api"),
    path("api/reports/global/", views.reports_global_api, name="reports_global_api"),
    path("api/reports/provider/<int:provider_id>/", views.reports_provider_api, name="reports_provider_api"),
    path("reports/lote/<int:batch_id>/pdf/", views.reports_lote_pdf, name="reports_lote_pdf"),
    path("reports/lote/<int:batch_id>/csv/", views.reports_lote_csv, name="reports_lote_csv"),
    path("reports/month/pdf/", views.reports_month_pdf, name="reports_month_pdf"),
    path("reports/month/csv/", views.reports_month_csv, name="reports_month_csv"),
    path("reports/global/pdf/", views.reports_global_pdf, name="reports_global_pdf"),
    path("reports/global/csv/", views.reports_global_csv, name="reports_global_csv"),
    path("reports/provider/<int:provider_id>/pdf/", views.reports_provider_pdf, name="reports_provider_pdf"),
    path("reports/provider/<int:provider_id>/csv/", views.reports_provider_csv, name="reports_provider_csv"),
    path("alerts/", views.alerts_view, name="alerts"),
    path("api/alerts/summary/", views.alerts_summary_api, name="alerts_summary_api"),
    path("api/alerts/list/", views.alerts_list_api, name="alerts_list_api"),
    path("api/alerts/active/", views.alerts_active_api, name="alerts_active_api"),
    path("api/alerts/<int:alert_id>/seen/", views.alert_mark_seen_api, name="alert_mark_seen_api"),
    path("api/alerts/<int:alert_id>/deactivate/", views.alert_deactivate_api, name="alert_deactivate_api"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/providers/", views.settings_providers, name="settings_providers"),
    path("settings/providers/create/", views.providers_create, name="providers_create"),
    path("settings/providers/<int:pk>/update/", views.providers_update, name="providers_update"),
    path("settings/providers/<int:pk>/delete/", views.providers_delete, name="providers_delete"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]
