# Generated by Django 6.0.2 on 2026-04-30 03:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('defect_type', models.CharField(choices=[('primary', 'Primario'), ('secondary', 'Secundario')], max_length=20)),
                ('equivalence', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Catálogo de defecto',
                'verbose_name_plural': 'Catálogo de defectos',
                'ordering': ['defect_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='QualitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size_grams', models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))])),
            ],
            options={
                'verbose_name': 'Configuración de calidad',
                'verbose_name_plural': 'Configuración de calidad',
            },
        ),
    ]
