# Generated by Django 6.0.2 on 2026-04-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_defectcatalog_qualitysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('official_count', models.PositiveIntegerField(default=0)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_results', to='dashboard.defectcatalog')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_results', to='dashboard.evaluation')),
            ],
            options={
                'verbose_name': 'Defecto detectado en evaluación',
                'verbose_name_plural': 'Defectos detectados en evaluaciones',
                'unique_together': {('evaluation', 'defect')},
            },
        ),
    ]
