# Generated by Django 6.0.2 on 2026-05-03 22:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_evaluationdefect'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoistureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_moisture', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('max_moisture', models.DecimalField(decimal_places=2, default=Decimal('12.50'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de humedad',
                'verbose_name_plural': 'Configuración de humedad',
            },
        ),
        migrations.CreateModel(
            name='MoistureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('result', models.CharField(choices=[('low_rejected', 'Rechazo por humedad baja'), ('optimal', 'Óptimo'), ('high_rejected', 'Rechazo por humedad alta')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moisture_analysis', to='dashboard.batch')),
            ],
            options={
                'verbose_name': 'Análisis de humedad',
                'verbose_name_plural': 'Análisis de humedad',
                'ordering': ['-created_at'],
            },
        ),
    ]
